name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código do repositório
        uses: actions/checkout@v2
        
      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'  # Corrigido para 'temurin'

      - name: Build e testar com Maven
        run: |
          mvn clean install
          mvn test
